shop/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('category/<slug:category_slug>/', views.home,
         name='event_by_category'),
    path('category/<slug:category_slug>/subcategory/<slug:subcategory_slug>/',
         views.home,
         name='event_by_subcategory'),
    path('category/<slug:category_slug>/subcategory/<slug:subcategory_slug>/'
         '<slug:event_slug>/',
         views.event_detail, name='event_detail'),
    path('account/signup/', views.signUp, name='signup'),
    path('account/login', views.signIn, name='login'),
    path('account/logout', views.signOut, name='logout'),
    path('cart', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:event_id>', views.add_cart, name='add_cart'),
    path('cart/remove/<int:event_id>', views.cart_remove, name='cart_remove'),
    path('cart/remove_product/<int:event_id>', views.cart_remove_product,
         name='cart_remove_product')
]

vovmark_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from vovmark_project import settings

urlpatterns = [
    path('', include('shop.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.


class Region(models.Model):
    region_name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.region_name

    class Meta:
        ordering = ('region_name',)
        verbose_name = 'Region'
        verbose_name_plural = 'Regions'


class City(models.Model):
    city_name = models.CharField(max_length=40)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    def __str__(self):
        return self.city_name

    class Meta:
        ordering = ('city_name',)
        verbose_name = 'City'
        verbose_name_plural = 'Cities'


class Category(models.Model):
    category_name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=250, unique=True)

    def get_url(self):
        return reverse('event_by_category', args=[self.slug])

    def __str__(self):
        return self.category_name

    class Meta:
        ordering = ('category_name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Subcategory(models.Model):
    subcategory_name = models.CharField(max_length=30)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=250)

    def get_url(self):
        return reverse('event_by_subcategory',
                       args=[self.category.slug, self.slug])

    def __str__(self):
        return self.category.category_name + "|" + self.subcategory_name

    class Meta:
        ordering = ('category',)
        verbose_name = 'Subcategory'
        verbose_name_plural = 'Subcategories'


class Event(models.Model):
    event_name = models.CharField(max_length=30)
    description = models.CharField(max_length=500)
    event_date = models.DateTimeField()
    event_cost = models.IntegerField(default=0)
    event_address = models.CharField(max_length=50)
    event_img = models.ImageField(upload_to="event_img/")
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=100)
    slug = models.SlugField(max_length=250, unique=True)

    def get_url(self):
        return reverse('event_detail', args=[self.subcategory.category.slug,
                                             self.subcategory.slug, self.slug])

    def __str__(self):
        return self.event_name

    class Meta:
        ordering = ('event_name',)


class Ticket(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)


class PaymentMethod(models.Model):
    name = models.CharField(max_length=50, unique=True)


class ShopCart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)


class CartItem(models.Model):
    # Maybe need to move field price from event to ticket???
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)
    shop_cart = models.ForeignKey(ShopCart, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=2, decimal_places=0)
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.event.event_cost * self.quantity

    def __str__(self):
        return self.event

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=50)
    email = forms.CharField(max_length=40, help_text='eg@mail.com')
    birth_date = forms.DateField(input_formats=['%d/%m/%y'],
                                 widget=forms.SelectDateWidget)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password1',
                  'password2', 'email', 'birth_date',)

shop/views.py
import random
from builtins import id

from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import Group, User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate

# Create your views here.

from .models import Event, Category, CartItem, ShopCart
from .forms import SignUpForm


def home(request, category_slug=None, subcategory_slug=None):
    if all((category_slug is not None, subcategory_slug is not None)):
        events = Event.objects.filter(subcategory__slug=subcategory_slug)
    elif category_slug is not None:
        category_page = get_object_or_404(Category, slug=category_slug)
        events = Event.objects.filter(subcategory__category=category_page)
    else:
        events = Event.objects.all()

    random_events = list(events)
    random.shuffle(random_events)

    return render(request, 'shop/index.html', {'events': random_events})


def event_detail(request, category_slug, subcategory_slug, event_slug):
    event = Event.objects.get(subcategory__slug=subcategory_slug,
                              slug=event_slug)
    return render(request, 'shop/event.html', {'event': event})


def signUp(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            signup_user = User.objects.get(username=username)
            user_group = Group.objects.get(name='User')
            user_group.user_set.add(signup_user)
    else:
        form = SignUpForm()

    return render(request, 'shop/signup.html', {'form': form})


def signIn(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                return redirect('signup')
    else:
        form = AuthenticationForm()
    return render(request, 'shop/login.html', {'form': form})


def signOut(request):
    logout(request)
    return redirect('login')


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, event_id):
    event = Event.objects.get(id=event_id)
    try:
        cart = ShopCart.objects.get(cart_id=_cart_id(request))
    except ShopCart.DoesNotExist:
        cart = ShopCart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(event=event, shop_cart=cart)
        if cart_item.quantity < cart_item.event.quantity:
            cart_item.quantity += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(event=event, quantity=1,
                                            shop_cart=cart)
        cart_item.save()

    return redirect('cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = ShopCart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(shop_cart=cart, active=True)
        for cart_item in cart_items:
            total += cart_item.event.event_cost * cart_item.quantity
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    return render(request, 'shop/cart.html', {'cart_items': cart_items,
                                              'total': total,
                                              'counter': counter})


def cart_remove(request, event_id):
    cart = ShopCart.objects.get(cart_id=_cart_id(request))
    event = get_object_or_404(Event, id=event_id)
    cart_item = CartItem.objects.get(event=event, shop_cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()

    return redirect('cart_detail')


def cart_remove_product(request, event_id):
    cart = ShopCart.objects.get(cart_id=_cart_id(request))
    event = get_object_or_404(Event, id=event_id)
    cart_item = CartItem.objects.get(event=event, shop_cart=cart)
    cart_item.delete()

    return redirect('cart_detail')

shop/templates/shop/base.html
    {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'shop/css/base.css' %}">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'shop/css/cart.css' %}">
	<title>{% block title %}{% endblock %}</title>
    <style type="text/css">
            .material-icons.md-48 { font-size: 48px; }
            .material-icons.md-24 { font-size: 24px; }
        </style>

</head>
<body>
<div class="all">
{% include 'shop/navbar.html' %}
{% include 'shop/menu.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'shop/footer.html' %}
    <script src="{% static 'shop/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'shop/js/masonry.pkgd.min.js' %}"></script>
    <script src="{% static 'shop/js/script.js' %}"></script>
</body>
</html>

shop/templates/shop/cart.html
{% extends 'shop/base.html' %}

{% load static %}

{% block title %}
Cart
{% endblock %}

{% block content %}
<div class="container">
    <div class="cart_block">
        {% if not cart_items %}
            <div class="cart_empty_block">
                <p class="grey_text">Your cart is empty</p>
                <p class="grey_text text_11px">Click <a href="{% url 'home' %}">here</a> to go back to home.</p>
            </div>
        {% else %}
            <p class="grey_text no_uppercase_text">Shopping cart</p>

                
                {% for cart_item in cart_items %}
                    <div class="bilet_buy_block bilet_buy_cart_block space_beetween">
                        <div class="event_foto_and_text_cart space_beetween">
                            <a class="event_foto_cart" href="{{ cart_item.event.get_url }}">
                                <img src="{{ cart_item.event.event_img.url }}">
                            </a>
                            <div>
                                <p>
                                {{ cart_item.event.event_name }}<br>
                                Unit price: {{ cart_item.event.event_cost }}<br>
                                Quantity: {{ cart_item.quantity }} x {{ cart_item.event.event_cost }}
                                </p>
                            </div>
                        </div>
                        {{ cart_item.sub_total }} zł

                        <div class="add_sub_del_event space_beetween">
                        {% if cart_item.quantity < cart_item.event.quantity %}
                            <a href="{% url 'add_cart' cart_item.event.id %}">
                                <i class="material-icons cart-icon">add_shopping_cart</i>
                            </a>
                            <a href="{% url 'cart_remove' cart_item.event.id %}">
                                <i class="material-icons cart-icon">remove_circle_outline</i>
                            </a>
                            <a href="{% url 'cart_remove_product' cart_item.event.id %}">
                                <i class="material-icons cart-icon">delete</i>
                            </a>
                        {% else %}
                            <a href="{% url 'cart_remove' cart_item.event.id %}"><i class="material-icons cart-icon">remove_circle_outline</i></a>
                            <a href="{% url 'cart_remove_product' cart_item.event.id %}"><i class="material-icons cart-icon">delete</i></a>
                        {% endif %}
                        </div>
                    </div>                    
                {% endfor %}



            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table cart-table">
                    <thead class="cart-thead">
                        <tr>
                            <th colspan="4">
                                Check out
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                Please check your cart before payment!
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                Your total bill is: <strong>{{ total }}$</strong>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="mx-auto">
                    <a href="{% url 'home' %}" style="text-decoration: None">
                        <button type="button" class="btn btn-lg btn-block bg-dark text-white">
                            Back to products
                        </button>
                    </a>
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

shop/templates/shop/event.html
{% extends 'shop/base.html' %}
{% block title %}
Ticket
{% endblock %}

{% block content %}
    <div class="backOpera ">
            <h1 class="big_wite_text"><b>Event</b> view</h1>
            <h3 class="big_wite_text sign_or_reg_text">{{ event.subcategory.category }} - {{ event.subcategory }} - {{ event.city }} - <span class="bue_green_text">{{ event.event_name }}</span></h3>
    </div>
    <div class="container">
       
        <div class="event_block space_beetween">
            <div class="left_part_event">
                <img src="{{ event.event_img.url }}">
            </div>
            <div class="right_part_event">
                <p  class="grey_text">{{ event.event_name }} - {{ event.city }}</p>
                <p class="event_all_text">The event will take place on: 
                    <br> Address: {{ event.event_address }} 
                    <br> {{ event.event_date.date }} at {{ event.event_date.time }}<br>
                    <br>{{ event.description }}</p>

                 <div class="bilet_block">
                    <div class="icon_and_name_event">
                        <i class="icon_ticket_big_in_event"></i>
                        <p class="grey_text no_uppercase_text">{{ event.event_name }} - {{ event.city }}</p>
                    </div>
                    <div class="bilet_buy_block space_beetween">
                        <div class="place_date_event_billet_buy">
                            <div class="go_left">
                                <p class="grey_text no_uppercase_text">{{ event.city }}</p>
                                <p class="grey_text no_uppercase_text">{{ event.event_date.date }}</p>
                            </div>
                            <div class="go_left plac_and_time_event_info">
                                <p class="grey_text text_13px no_uppercase_text">{{ event.event_date.time }}</p>
                                <p class="grey_text text_13px no_uppercase_text">{{ event.event_address }}</p>
                            </div>
                        </div>


                    {% if event.quantity > 0 %}
                            <a class="some_bot" href="{% url 'add_cart' event.id %}">
                                 <p class="bot_text_white"> Add to cart</p>
                            </a>
                        {% else %}
                            <p class="bue_green_text">Sold out! :)</p>
                        {% endif %}    
                    </div>
                </div>
            </div>
        </div>        
    </div>  
{% endblock %}

shop/templates/shop/footer.html
<footer>
			<div class="container">
				<div class="before_footer">
					<div class="footer_menu">
						<span class="nav_link">Information</span>
						<p><a href="#">Infa</a></p>
						<p><a href="#">Nuzna</a></p>
						<p><a href="#">Tut</a></p>
						<p><a href="#">Pustowato</a></p>
						<p><a href="#">Help</a></p>
					</div>
					<div class="footer_menu">
						<span class="nav_link">Information</span>
						<p><a href="#">Infa</a></p>
						<p><a href="#">Nuzna</a></p>
						<p><a href="#">Tut</a></p>
						<p><a href="#">Pustowato</a></p>
						<p><a href="#">Help</a></p>
					</div>
					<div class="footer_menu">
						<span class="nav_link">Information</span>
						<p><a href="#">Infa</a></p>
						<p><a href="#">Nuzna</a></p>
						<p><a href="#">Tut</a></p>
						<p><a href="#">Pustowato</a></p>
						<p><a href="#">Help</a></p>
					</div>
					<div class="footer_menu">
						<span class="nav_link">Information</span>
						<p><a href="#">Infa</a></p>
						<p><a href="#">Nuzna</a></p>
						<p><a href="#">Tut</a></p>
						<p><a href="#">Pustowato</a></p>
						<p><a href="#">Help</a></p>
					</div>
					<div class="footer_menu footer_menu_300">
						<span class="nav_link">contact details</span>
						<p>Head Office: Avenue Fashion, 180-182 Regent Street, London.</p>
						<p>Telephone: 0123-456-789</p>
						<p>Email: support@yourwebsite.com</p>
					</div>
				</div>
			</div>
			<div class="foot space_beetween">
				<div class="container">
					<div class="foot space_beetween">
						<div><p>2020 Vlark gr. 3.9/17</p></div>
						<div>
							<p>Design by Volodymyr & Mark</p>
							<p>Dev by Volodymyr</p>
						</div>
					</div>
				</div>
			</div>
		</footer>

shop/templates/shop/index.html
{% extends 'shop/base.html' %}

{% load static %}

{% block title %}
    Vlark
{% endblock %}

{% block content %}
<body>
	<div class="intro">
		<div class="backMain">
			<div class="container">	
				<div class="intro_inner">
					<a class="btn btn_festival" href="http://ignacyjanpaderewski.com/"><p>Odwiedź festiwal</p></a>
				</div>
			</div>
		</div>
	</div>

	<div class="main_part">
		<div class="container con_1400">
			<nav  class="nav_menu nav_gallery">
				<a class="nav_link" href="#"><p>popular</p></a>
				<a class="nav_link" href="#"><p>new arrivals </p></a>
				<a class="nav_link" href="#"><p>best sellers</p></a>
				<a class="nav_link" href="#"><p>special offers</p></a>
				<a class="nav_link" href="#"><p>coming soon</p></a>
			</nav>
            {% if events %}
            <div class="gallery">
                    {% for event in events %}
                        <a class="gimg" href="{{ event.get_url }}" >
                            <div class="event_info">
                                <div class="event_name">
                                    <p class="name">{{ event.event_name }}</p>
                                </div>
                                <div class="event_main">
                                    <div class="date">
                                        <span class="date_icon icons"></span>
                                        <p>{{ event.event_date.date }}</p>
                                    </div>
                                    <div class="location">
                                        <span class="place_icon icons"></span>
                                        <p>{{ event.event_address }}</p>
                                    </div>
                                    <div class="price">
                                        <span class="price_icon icons"></span>
                                        <p>{{ event.event_cost }}</p>
                                    </div>
                                </div>
                            </div>
                            <img src="{{ event.event_img.url }}" alt="BB">
                        </a>
                    {% endfor %}
            </div>
            {% else %}
                <h1>Sorry, we haven't this kind of events yet. Go <a href="{% url 'home' %}">Home</a></h1>
            {% endif %}
		</div>
    </div>


    {% include 'shop/teach.html' %}
</body>
{% endblock %}

shop/templates/shop/login.html
{% extends 'shop/base.html' %}
{% load crispy_forms_filters %}


{% load crispy_forms_tags %}

{% block title %}
Log In
{% endblock %}

{% block content %}

    <div class="backOpera">
        <h1 class="big_wite_text"><b>WELCOME</b> to vlark</h1>
        <h3 class="big_wite_text sign_or_reg_text">sign in or register</h3>
    </div>

    <div class="container">
        <div class="login_block">
            <p class="grey_text">Login User</p>
            <p class="grey_text text_13px">Registered Users only</p>

            <form method="post">
                <div class="forma">
                    {% csrf_token %}
                    {{ form|crispy }}
                </div>
                <div class="space_beetween">
                    <button type="submit" class="some_bot btn-secondary">
                        <p class="bot_text_white">Log in</p>
                    </button>
                    <a class="bue_green_text" href="{% url 'signup' %}"><p>or create an account...</p></a>
                </div>
            </form>
        </div>
    </div>  
{% endblock %}

shop/templates/shop/menu.html
{% load static %}

<body>
    <div class="menu">
		<div class="container">
			<div class="inner space_beetween">
				<div class="logo"></div>
				<nav  class="nav_menu">
                    {% for category in categories %}
					<div class="menu_list">
						<a class="nav_link" href="{{ category.get_url }}"><p>{{ category.category_name }}</p>
							<span class="arrow-bot"></span>
						</a>
						<div class="for_hov">
							<ul class="sub_menu_list">
                                {% for subcategory in category.subcategory_set.all %}
								<li><a href="{{ subcategory.get_url }}">{{ subcategory.subcategory_name }}</a></li>
                                {% endfor %}
							</ul>
						</div>
					</div>
                    {% endfor %}
				</nav>
			</div>
		</div>
	</div>
	<script src="{% static 'shop/js/jquery-3.5.1.min.js' %}"></script>
	<script>
		var s_win_w = window.innerWidth;

		function resize(){
			var forH = document.getElementsByClassName('for_hov');
			var i;
			var otsup = 0;
			var otsupInPx = "";

			for(i = 0; i < forH.length; i++){
				otsup = ((window.innerWidth - 1000)/2) + 120 * (forH.length - i) - 510;
				if(otsup <= 0){
					otsup = 50;
				}
				otsupInPx = otsup.toString() + "px";
				forH[i].style.right = otsupInPx;
			}
		}
		
		$(window).resize(function(){		  	
	    	resize();

		});

		(function(){
    		resize();
		})();
	</script>
</body>

shop/templates/shop/navbar.html
{% load static %}

<body>
    <header class="header">
		<div class="container">
			<div class="inner space_beetween">
				<div class="logo"><a href="{% url 'home' %}">Vlark</a></div>
				<nav  class="nav">
                    {% if not request.user.is_authenticated %}
					<a class="nav_link" href="{% url 'signup' %}"><p>Register</p></a>
					<a class="nav_link" href="{% url 'login' %}"><p>Log In</p></a>
                    {% else %}
                        <a class="nav_link" href="{% url 'logout' %}"><p>Log Out</p></a>
                    {% endif %}
					<a class="nav_link empty" href="{% url 'cart_detail' %}">
						<img class="car" src="{% static 'shop/images_for_pages/shop_cart.png' %}" alt="S">
                        {% if item_count > 0 %}
                            <p>{{ item_count }}</p>
                        {% else %}
                        	<p>Empty</p>
                        {% endif %}
						<span class="arrow-bot"></span>
					</a>
				</nav>
			</div>
		</div>
	</header>
</body>

shop/templates/shop/signup.html
{% extends 'shop/base.html' %}
{% load crispy_forms_filters %}

{% load static %}

{% load crispy_forms_tags %}


{% block title %}
    Create New Account
{% endblock %}

{% block content %}
    
     <div class="backOpera">
        <h1 class="big_wite_text"><b>WELCOME</b> to vlark</h1>
        <h3 class="big_wite_text sign_or_reg_text">sign in or register</h3>
    </div>

    <div class="container">
        <div class="signup_block">
            {% if not form.is_valid %}
                <p class="grey_text">Create a new Account</p>
                <p class="grey_text text_11px">Please input the following information to create a new account</p>

                <form method="post">
                     <div class="forma clear">
                        <div id="registerLeft" class="half_big_forma"></div>
                        <div class="palka"></div>
                        <div id="registerRight" class="half_big_forma"></div>
                        {% csrf_token %}
                        {{ form|crispy }}
                    </div>
                    <button id="button_reg" type="submit" class="some_bot">
                        <p class="bot_text_white">Sign up</p>
                    </button>
                </form>
            {% else %}
                <div>
                    <p class="grey_text">Your account has been successfully created</p>
                    <div>
                        <p class="grey_text text_13px">Your account has been created and ready to use</p>
                        <a class="or_creat_text" href="{% url 'home' %}">Continue</a>
                    </div>
                </div>
            {% endif %}
        </div>  
        <script>
            var en = document.getElementById("div_id_first_name");
            registerLeft.appendChild(en);

            en = document.getElementById("div_id_last_name");
            registerLeft.appendChild(en);

            en = document.getElementById("div_id_username");
            registerLeft.appendChild(en);

            en = document.getElementById("div_id_email");
            registerLeft.appendChild(en);

            en = document.getElementById("div_id_email");
            registerLeft.appendChild(en);

             en = document.getElementById("div_id_birth_date");
            registerLeft.appendChild(en);

            en = document.getElementById("div_id_password1");
            registerRight.appendChild(en);

            en = document.getElementById("div_id_password2");
            registerRight.appendChild(en);

            en = document.getElementById("button_reg");
            registerRight.appendChild(en);

        </script>
    </div>
{% endblock %}

shop/templates/shop/teach.html
<div class="teach">
			<div class="container con_1500">
				<div class="trio space_beetween">
					<div class="after_gallery">
						<div class="some_foto">

						</div>
						<div class="some_name">
							<p><span class="some_select">men’s</span><br>lookbook</p>
						</div>
						<div class="some_description">
							<p>Lorem ipsum dolor sit amet eras facilisis consectetur adipiscing elit lor, integer lorem consecteur dignissim laciniqui.Elementum metus facilisis ut phasellu.
							</p>
						</div>
						<a class="some_bot bot_view_now" href="#">
							<p class="bot_text_white">view now</p>
						</a>
					</div>
					<div class="after_gallery">
						<div class="some_foto">

						</div>
						<div class="some_name">
							<p><span class="some_select">women’s</span><br>lookbook</p>
						</div>
						<div class="some_description">
							<p>Pellentesque habitant morbi tristique senectus et netus et malesuada ames . Pellentesque laoreet quis enim et mattis. Quisque interdum felis ellus.
							</p>
						</div>
						<a class="some_bot bot_view_now" href="#">
							<p class="bot_text_white">view now</p>
						</a>
					</div>
					<div class="after_gallery">
						<div class="some_foto">

						</div>
						<div class="some_name">
							<p><span class="some_select">your</span><br>lookbook</p>
						</div>
						<div class="some_description">
							<p>See an item you like and click the button to add it to your lookbook where you can create your own perfect look. It’s like your own boutique!
							</p>
						</div>
						<a class="some_bot bot_view_now" href="#">
							<p class="bot_text_white">view now</p>
						</a>
					</div>
				</div>
			</div>
		</div>